import Foundation

// The Screenshot, Pointer and Ruler pages, and the panels they open. English
// values live in Resources/en.lproj/Localizable.strings.

extension LocalizedStringResource {
    static let shotCapture = Self.key("shot.capture")
    static let shotCaptureRegion = Self.key("shot.captureRegion")
    static let shotCaptureWindow = Self.key("shot.captureWindow")
    static let shotCaptureScreen = Self.key("shot.captureScreen")
    static let shotCaptureHelp = Self.key("shot.captureHelp")
    static let shotPinPart = Self.key("shot.pinPart")
    static let shotPinPartHelp = Self.key("shot.pinPartHelp")
    static let shotLanguage = Self.key("shot.language")
    static let shotLanguageAutomatic = Self.key("shot.languageAutomatic")
    static let shotText = Self.key("shot.text")
    static let shotTextHelp = Self.key("shot.textHelp")
    static let shotOutput = Self.key("shot.output")
    static let shotCopyOnSave = Self.key("shot.copyOnSave")
    static let shotSaveFolder = Self.key("shot.saveFolder")

    static let mousePointerHelp = Self.key("mouse.pointerHelp")
    static let mouseClicks = Self.key("mouse.clicks")
    static let mouseRingClicks = Self.key("mouse.ringClicks")
    static let mouseRingClicksHelp = Self.key("mouse.ringClicksHelp")
    static let mouseColour = Self.key("mouse.colour")
    static let mouseColourFollowsZones = Self.key("mouse.colourFollowsZones")
    static let mouseColourCustom = Self.key("mouse.colourCustom")
    static let mouseUseTheZoneColour = Self.key("mouse.useTheZoneColour")
    static let mouseRightColour = Self.key("mouse.rightColour")
    static let mouseRightColourFollows = Self.key("mouse.rightColourFollows")
    static let mouseMatchLeftClicks = Self.key("mouse.matchLeftClicks")
    static let mouseShape = Self.key("mouse.shape")
    static let mouseShapeRing = Self.key("mouse.shapeRing")
    static let mouseShapeDot = Self.key("mouse.shapeDot")
    static let mouseShapeBoth = Self.key("mouse.shapeBoth")
    static let mouseSize = Self.key("mouse.size")
    static let mouseSizeHelp = Self.key("mouse.sizeHelp")
    static let mouseThickness = Self.key("mouse.thickness")
    static let mouseThicknessHelp = Self.key("mouse.thicknessHelp")
    static let mouseFade = Self.key("mouse.fade")
    static let mouseFadeHelp = Self.key("mouse.fadeHelp")
    static let mouseCrosshairsCard = Self.key("mouse.crosshairsCard")
    static let mouseCrosshairs = Self.key("mouse.crosshairs")
    static let mouseCrosshairsHelp = Self.key("mouse.crosshairsHelp")
    static let mouseOpacity = Self.key("mouse.opacity")
    static let mouseFinding = Self.key("mouse.finding")
    static let mouseFindingHelp = Self.key("mouse.findingHelp")
    static let mouseCircle = Self.key("mouse.circle")
    static let mouseCircleHelp = Self.key("mouse.circleHelp")
    static let mouseDimming = Self.key("mouse.dimming")
    static let mouseDimmingHelp = Self.key("mouse.dimmingHelp")
    static let mouseShortcutsHelp = Self.key("mouse.shortcutsHelp")
}
