import Foundation

// Home, Zones and Appearance. English values live in
// Resources/en.lproj/Localizable.strings.

extension LocalizedStringResource {
    static let homeReady = Self.key("home.ready")
    static let homeHeadline = Self.key("home.headline")
    static let homeTagline = Self.key("home.tagline")
    static let homeShowZones = Self.key("home.showZones")
    static let homeEditZonesButton = Self.key("home.editZonesButton")
    static let homeQuickActions = Self.key("home.quickActions")
    static let homeCaptureRegion = Self.key("home.captureRegion")
    static let homeEditZones = Self.key("home.editZones")
    static let homeAwakeOn = Self.key("home.awakeOn")
    static let homeKeepAwake = Self.key("home.keepAwake")
    static let homeWhatIsOn = Self.key("home.whatIsOn")
    static let homeHotkeys = Self.key("home.hotkeys")
    static let homeHotkeysDetail = Self.key("home.hotkeysDetail")
    static let homeDragToSnap = Self.key("home.dragToSnap")
    static let homeDragToSnapDetail = Self.key("home.dragToSnapDetail")
    static let homeKeepAwakeDetail = Self.key("home.keepAwakeDetail")
    static let homeKeepAwakePaused = Self.key("home.keepAwakePaused")
    static let homeLaunchAtLogin = Self.key("home.launchAtLogin")
    static let homeLaunchAtLoginDetail = Self.key("home.launchAtLoginDetail")
    static let homePrivacy = Self.key("home.privacy")
    static let homeEdgeSnapping = Self.key("home.edgeSnapping")
    static let homeRectangleTitle = Self.key("home.rectangleTitle")
    static let homeRectangleDetail = Self.key("home.rectangleDetail")
    static let homeRectangleTake = Self.key("home.rectangleTake")
    static let homeRectangleNotNow = Self.key("home.rectangleNotNow")
    static let homeRectangleMore = Self.key("home.rectangleMore")

    static func homeHotkeysTaken(_ names: String) -> LocalizedStringResource {
        Self.key("home.hotkeysTaken \(names)")
    }

    static let zonesDragging = Self.key("zones.dragging")
    static let zonesDraggingHelp = Self.key("zones.draggingHelp")
    static let zonesDragToSnap = Self.key("zones.dragToSnap")
    static let zonesDragToSnapDetail = Self.key("zones.dragToSnapDetail")
    static let zonesShowZones = Self.key("zones.showZones")
    static let zonesWhileDragging = Self.key("zones.whileDragging")
    static let zonesWithTheModifier = Self.key("zones.withTheModifier")
    static let zonesModifier = Self.key("zones.modifier")
    static let zonesModifierShift = Self.key("zones.modifierShift")
    static let zonesModifierOption = Self.key("zones.modifierOption")
    static let zonesModifierCommand = Self.key("zones.modifierCommand")
    static let zonesModifierControl = Self.key("zones.modifierControl")
    static let zonesShakeToSnap = Self.key("zones.shakeToSnap")
    static let zonesShakeToSnapDetail = Self.key("zones.shakeToSnapDetail")
    static let zonesPresets = Self.key("zones.presets")
    static let zonesDisplaysAndSize = Self.key("zones.displaysAndSize")
    static let zonesDisplaysAndSizeHelp = Self.key("zones.displaysAndSizeHelp")
    static let zonesKeys = Self.key("zones.keys")
    static let zonesCycleHalves = Self.key("zones.cycleHalves")
    static let zonesCycleHalvesDetail = Self.key("zones.cycleHalvesDetail")
    static let zonesNumbered = Self.key("zones.numbered")
    static let zonesNumberedHelp = Self.key("zones.numberedHelp")
    static let zonesSwitching = Self.key("zones.switching")
    static let zonesSwitchingHelp = Self.key("zones.switchingHelp")
    static let zonesFocus = Self.key("zones.focus")
    static let zonesFocusHelp = Self.key("zones.focusHelp")
    static let zonesDesktopChanges = Self.key("zones.desktopChanges")
    static let zonesRestoreOnDisplayChange = Self.key("zones.restoreOnDisplayChange")
    static let zonesRestoreOnDisplayChangeDetail = Self.key("zones.restoreOnDisplayChangeDetail")
    static let zonesRestoreEveryWindow = Self.key("zones.restoreEveryWindow")
    static let zonesRestoreEveryWindowDetail = Self.key("zones.restoreEveryWindowDetail")
    static let zonesPlaceNewWindows = Self.key("zones.placeNewWindows")
    static let zonesPlaceNewWindowsDetail = Self.key("zones.placeNewWindowsDetail")
    static let zonesAutoFill = Self.key("zones.autoFill")
    static let zonesAutoFillDetail = Self.key("zones.autoFillDetail")
    static let zonesRules = Self.key("zones.rules")
    static let zonesRulesHelp = Self.key("zones.rulesHelp")
    static let rulesNone = Self.key("rules.none")
    static let rulesThisScreen = Self.key("rules.thisScreen")
    static let rulesScreenAway = Self.key("rules.screenAway")
    static let rulesRemove = Self.key("rules.remove")
    static let zonesPageHelp = Self.key("zones.pageHelp")
    static let zonesShortcutsHelp = Self.key("zones.shortcutsHelp")
    static let zonesOverlay = Self.key("zones.overlay")
    static let zonesOverlayHelp = Self.key("zones.overlayHelp")
    static let zonesGap = Self.key("zones.gap")
    static let zonesGapHelp = Self.key("zones.gapHelp")
    static let zonesOpacity = Self.key("zones.opacity")
    static let zonesColour = Self.key("zones.colour")
    static let zonesColourFollowsAccent = Self.key("zones.colourFollowsAccent")
    static let zonesColourCustom = Self.key("zones.colourCustom")
    static let zonesUseTheAccent = Self.key("zones.useTheAccent")
    static let zonesNumberTheZones = Self.key("zones.numberTheZones")
    static let zonesEveryMonitor = Self.key("zones.everyMonitor")
    static let zonesEdgeSpanning = Self.key("zones.edgeSpanning")
    static let zonesEdgeSpanningHelp = Self.key("zones.edgeSpanningHelp")
    static let zonesGrabMove = Self.key("zones.grabMove")
    static let zonesGrabMoveHelp = Self.key("zones.grabMoveHelp")
    static let zonesGrabAnywhere = Self.key("zones.grabAnywhere")
    static let zonesGrabAnywhereDetail = Self.key("zones.grabAnywhereDetail")
    static let zonesHold = Self.key("zones.hold")
    static let zonesRightDragResizes = Self.key("zones.rightDragResizes")
    static let zonesRightDragResizesDetail = Self.key("zones.rightDragResizesDetail")
    static let zonesShowSizeWhileDragging = Self.key("zones.showSizeWhileDragging")
    static let zonesExclusions = Self.key("zones.exclusions")
    static let zonesExclusionsHelp = Self.key("zones.exclusionsHelp")

    static let appearancePageHelp = Self.key("appearance.pageHelp")
    static let appearanceTheme = Self.key("appearance.theme")
    static let appearanceThemeNote = Self.key("appearance.themeNote")
    static let appearanceAccent = Self.key("appearance.accent")
    static let appearanceAccentNote = Self.key("appearance.accentNote")
    static let appearanceMatchSystemAccent = Self.key("appearance.matchSystemAccent")
    static let appearanceFollowSystemAccent = Self.key("appearance.followSystemAccent")
    static let appearanceThemeSystem = Self.key("appearance.themeSystem")
    static let appearanceThemeLight = Self.key("appearance.themeLight")
    static let appearanceThemeDark = Self.key("appearance.themeDark")
    static let appearanceThemeSystemNote = Self.key("appearance.themeSystemNote")
    static let appearanceThemeLightNote = Self.key("appearance.themeLightNote")
    static let appearanceThemeDarkNote = Self.key("appearance.themeDarkNote")

    static func appearanceThemeHelp(_ title: String, _ note: String) -> LocalizedStringResource {
        Self.key("appearance.themeHelp \(title) \(note)")
    }

    static let homeConnectedAgents = Self.key("home.connectedAgents")
    static let homeNoAgentYet = Self.key("home.noAgentYet")
    static let homeSetOneUp = Self.key("home.setOneUp")
    static let homeDriving = Self.key("home.driving")
    static let homeIdle = Self.key("home.idle")
    static let homeOnlySelectedDrives = Self.key("home.onlySelectedDrives")
    static let homeListening = Self.key("home.listening")
    static let homeToken = Self.key("home.token")
    static let homeTokenStored = Self.key("home.tokenStored")
    static let homeReveal = Self.key("home.reveal")
    static let homeLoopbackOnly = Self.key("home.loopbackOnly")

    static let startTitle = Self.key("start.title")
    static let startHide = Self.key("start.hide")
    static let startHideHelp = Self.key("start.hideHelp")
    static let startGrant = Self.key("start.grant")
    static let startGrantDetail = Self.key("start.grantDetail")
    static let startRecord = Self.key("start.record")
    static let startRecordDetail = Self.key("start.recordDetail")
    static let startNeverAsked = Self.key("start.neverAsked")
    static let startSnap = Self.key("start.snap")
    static let startSnapDetail = Self.key("start.snapDetail")
    static let startAgent = Self.key("start.agent")
    static let startAgentDetail = Self.key("start.agentDetail")
    static let startGrantButton = Self.key("start.grantButton")
    static let startShowZones = Self.key("start.showZones")
    static let startCopied = Self.key("start.copied")
    static let startCopyCommand = Self.key("start.copyCommand")
    static let startHow = Self.key("start.how")

    static func startProgress(_ done: Int, _ total: Int) -> LocalizedStringResource {
        Self.key("start.progress \(done) \(total)")
    }
}
