#!/usr/bin/env swift
// Draws the README's demo animation, frame by frame, and leaves the PNGs for
// ffmpeg to turn into a GIF. Run it through scripts/make-demo.sh.
//
// A rendered animation rather than a screen recording, on purpose: a recording
// of a window manager is mostly other people's apps, it dates the moment any of
// them is redesigned, and it cannot be regenerated by anyone reading this repo.
// This can — it is one file, and every frame is a pure function of time.

import AppKit
import CoreText

// MARK: - Timeline

let fps = 20.0
let duration = 9.0
let size = CGSize(width: 1200, height: 750)

/// 0 at `from`, 1 at `to`, eased so movement starts and stops softly.
func phase(_ t: Double, from: Double, to: Double) -> Double {
    guard to > from else { return t >= to ? 1 : 0 }
    let raw = min(max((t - from) / (to - from), 0), 1)
    return raw < 0.5 ? 4 * raw * raw * raw : 1 - pow(-2 * raw + 2, 3) / 2
}

func lerp(_ a: Double, _ b: Double, _ t: Double) -> Double { a + (b - a) * t }

func lerp(_ a: CGRect, _ b: CGRect, _ t: Double) -> CGRect {
    CGRect(x: lerp(a.minX, b.minX, t), y: lerp(a.minY, b.minY, t),
           width: lerp(a.width, b.width, t), height: lerp(a.height, b.height, t))
}

// MARK: - Palette

enum Ink {
    static let desk = NSColor(srgbRed: 0.07, green: 0.08, blue: 0.11, alpha: 1)
    static let deskGlow = NSColor(srgbRed: 0.13, green: 0.15, blue: 0.22, alpha: 1)
    static let bar = NSColor(srgbRed: 0.10, green: 0.11, blue: 0.15, alpha: 0.96)
    static let accent = NSColor(srgbRed: 0.35, green: 0.62, blue: 1.0, alpha: 1)
    static let amber = NSColor(srgbRed: 1.0, green: 0.72, blue: 0.30, alpha: 1)
    static let chrome = NSColor(srgbRed: 0.17, green: 0.19, blue: 0.24, alpha: 1)
    static let pane = NSColor(srgbRed: 0.12, green: 0.13, blue: 0.17, alpha: 1)
    static let text = NSColor(white: 0.92, alpha: 1)
    static let dim = NSColor(white: 0.55, alpha: 1)
}

// MARK: - Drawing helpers

func fill(_ rect: CGRect, _ color: NSColor, radius: CGFloat = 0, in ctx: CGContext) {
    ctx.setFillColor(color.cgColor)
    ctx.addPath(CGPath(roundedRect: rect, cornerWidth: radius, cornerHeight: radius, transform: nil))
    ctx.fillPath()
}

func stroke(_ rect: CGRect, _ color: NSColor, radius: CGFloat = 0, width: CGFloat = 1,
            in ctx: CGContext) {
    ctx.setStrokeColor(color.cgColor)
    ctx.setLineWidth(width)
    ctx.addPath(CGPath(roundedRect: rect.insetBy(dx: width / 2, dy: width / 2),
                       cornerWidth: radius, cornerHeight: radius, transform: nil))
    ctx.strokePath()
}

enum Align { case left, centre }

func text(_ string: String, at point: CGPoint, size fontSize: CGFloat, color: NSColor,
          weight: NSFont.Weight = .regular, align: Align = .left,
          mono: Bool = false, in ctx: CGContext) {
    let font = mono
        ? NSFont.monospacedSystemFont(ofSize: fontSize, weight: weight)
        : NSFont.systemFont(ofSize: fontSize, weight: weight)
    let attributed = NSAttributedString(string: string, attributes: [
        .font: font, .foregroundColor: color,
    ])
    let line = CTLineCreateWithAttributedString(attributed)
    var x = point.x
    if align == .centre {
        x -= CTLineGetTypographicBounds(line, nil, nil, nil) / 2
    }
    ctx.textPosition = CGPoint(x: x, y: point.y)
    CTLineDraw(line, ctx)
}

func width(of string: String, size fontSize: CGFloat, weight: NSFont.Weight = .regular,
           mono: Bool = false) -> CGFloat {
    let font = mono
        ? NSFont.monospacedSystemFont(ofSize: fontSize, weight: weight)
        : NSFont.systemFont(ofSize: fontSize, weight: weight)
    let attributed = NSAttributedString(string: string, attributes: [.font: font])
    return CTLineGetTypographicBounds(CTLineCreateWithAttributedString(attributed), nil, nil, nil)
}

// MARK: - Pieces of the picture

/// The desk: a dark screen with a menu bar and Plonk's cube in it.
func drawDesk(in ctx: CGContext) {
    fill(CGRect(origin: .zero, size: size), Ink.desk, in: ctx)
    // A soft pool of light behind everything, so the flat colours have somewhere to sit.
    let glow = CGGradient(colorsSpace: CGColorSpaceCreateDeviceRGB(),
                          colors: [Ink.deskGlow.cgColor, Ink.desk.cgColor] as CFArray,
                          locations: [0, 1])!
    ctx.drawRadialGradient(glow, startCenter: CGPoint(x: size.width / 2, y: size.height * 0.62),
                           startRadius: 0, endCenter: CGPoint(x: size.width / 2, y: size.height * 0.62),
                           endRadius: size.width * 0.62, options: [])

    let bar = CGRect(x: 0, y: size.height - 34, width: size.width, height: 34)
    fill(bar, Ink.bar, in: ctx)
    // The cube, drawn small: two faces and a top, same shape as the status icon.
    let cube = CGRect(x: size.width - 58, y: size.height - 25, width: 16, height: 16)
    fill(CGRect(x: cube.minX, y: cube.minY, width: 16, height: 11), Ink.amber, radius: 2, in: ctx)
    fill(CGRect(x: cube.minX + 3, y: cube.minY + 8, width: 10, height: 6),
         Ink.amber.withAlphaComponent(0.55), radius: 2, in: ctx)
    text("Plonk", at: CGPoint(x: 20, y: size.height - 23), size: 13, color: Ink.dim,
         weight: .semibold, in: ctx)
}

struct Pane {
    var title: String
    var rect: CGRect
    var hue: NSColor
}

/// A window: title bar, three lights, a few lines of content.
func draw(_ pane: Pane, alpha: CGFloat = 1, in ctx: CGContext) {
    ctx.saveGState()
    ctx.setAlpha(alpha)
    ctx.setShadow(offset: CGSize(width: 0, height: -6), blur: 22,
                  color: NSColor.black.withAlphaComponent(0.55).cgColor)
    fill(pane.rect, Ink.pane, radius: 10, in: ctx)
    ctx.setShadow(offset: .zero, blur: 0, color: nil)
    stroke(pane.rect, NSColor(white: 1, alpha: 0.09), radius: 10, in: ctx)

    let chrome = CGRect(x: pane.rect.minX, y: pane.rect.maxY - 30, width: pane.rect.width, height: 30)
    ctx.saveGState()
    ctx.addPath(CGPath(roundedRect: pane.rect, cornerWidth: 10, cornerHeight: 10, transform: nil))
    ctx.clip()
    fill(chrome, Ink.chrome, in: ctx)
    ctx.restoreGState()

    for (index, colour) in [NSColor(srgbRed: 1, green: 0.37, blue: 0.34, alpha: 1),
                            NSColor(srgbRed: 1, green: 0.74, blue: 0.18, alpha: 1),
                            NSColor(srgbRed: 0.24, green: 0.79, blue: 0.33, alpha: 1)].enumerated() {
        fill(CGRect(x: chrome.minX + 14 + CGFloat(index) * 16, y: chrome.midY - 4.5,
                    width: 9, height: 9), colour, radius: 4.5, in: ctx)
    }
    text(pane.title, at: CGPoint(x: chrome.minX + 68, y: chrome.midY - 5), size: 12,
         color: Ink.dim, weight: .medium, in: ctx)

    // Content: a coloured header rule, then grey lines that fit the width.
    let body = pane.rect.insetBy(dx: 18, dy: 0)
    var y = chrome.minY - 26
    fill(CGRect(x: body.minX, y: y, width: min(body.width * 0.42, 150), height: 7),
         pane.hue.withAlphaComponent(0.9), radius: 3.5, in: ctx)
    y -= 20
    let widths: [CGFloat] = [0.9, 0.66, 0.82, 0.5, 0.74, 0.6, 0.86, 0.44, 0.78]
    var index = 0
    // Filled to the bottom rather than to a fixed count: a window with a third
    // of its content drawn reads as a window that is still loading.
    while y > pane.rect.minY + 18 {
        fill(CGRect(x: body.minX, y: y, width: body.width * widths[index % widths.count], height: 5),
             NSColor(white: 1, alpha: 0.13), radius: 2.5, in: ctx)
        // A paragraph break every so often, so it reads as text and not a barcode.
        y -= (index % 5 == 4) ? 26 : 15
        index += 1
    }
    ctx.restoreGState()
}

/// The zone overlay, as the app draws it: rounded tiles, numbered, one lit.
func drawZones(_ zones: [CGRect], highlighted: Set<Int>, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    for (index, zone) in zones.enumerated() {
        let lit = highlighted.contains(index)
        fill(zone, Ink.accent.withAlphaComponent(lit ? 0.28 : 0.10), radius: 10, in: ctx)
        stroke(zone, Ink.accent.withAlphaComponent(lit ? 0.95 : 0.4), radius: 10,
               width: lit ? 2.5 : 1.5, in: ctx)
        text("\(index + 1)", at: CGPoint(x: zone.midX, y: zone.midY - 20), size: 54,
             color: Ink.accent.withAlphaComponent(lit ? 0.95 : 0.38), weight: .bold,
             align: .centre, in: ctx)
    }
    ctx.restoreGState()
}

/// A row of key caps, e.g. ⌃⌥2.
func drawKeys(_ keys: [String], centeredAt point: CGPoint, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    let capHeight: CGFloat = 46
    let caps = keys.map { max(capHeight, width(of: $0, size: 22, weight: .semibold) + 26) }
    let total = caps.reduce(0, +) + CGFloat(keys.count - 1) * 8
    var x = point.x - total / 2
    for (index, key) in keys.enumerated() {
        let rect = CGRect(x: x, y: point.y, width: caps[index], height: capHeight)
        fill(rect, NSColor(white: 0.16, alpha: 0.96), radius: 9, in: ctx)
        stroke(rect, NSColor(white: 1, alpha: 0.16), radius: 9, in: ctx)
        text(key, at: CGPoint(x: rect.midX, y: rect.midY - 9), size: 22, color: Ink.text,
             weight: .semibold, align: .centre, in: ctx)
        x += caps[index] + 8
    }
    ctx.restoreGState()
}

/// The pointer, drawn rather than screenshotted so it renders at any size.
func drawCursor(at point: CGPoint, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    ctx.setShadow(offset: CGSize(width: 0, height: -2), blur: 6,
                  color: NSColor.black.withAlphaComponent(0.6).cgColor)
    let path = CGMutablePath()
    path.move(to: point)
    path.addLine(to: CGPoint(x: point.x, y: point.y - 26))
    path.addLine(to: CGPoint(x: point.x + 6.5, y: point.y - 19.5))
    path.addLine(to: CGPoint(x: point.x + 11, y: point.y - 28))
    path.addLine(to: CGPoint(x: point.x + 16, y: point.y - 25.5))
    path.addLine(to: CGPoint(x: point.x + 11.5, y: point.y - 17))
    path.addLine(to: CGPoint(x: point.x + 20, y: point.y - 16))
    path.closeSubpath()
    ctx.addPath(path)
    ctx.setFillColor(NSColor.white.cgColor)
    ctx.fillPath()
    ctx.restoreGState()
}

/// The agent's line, typed out a character at a time.
func drawPrompt(_ line: String, progress: Double, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    let shown = String(line.prefix(Int(Double(line.count) * min(max(progress, 0), 1))))
    let box = CGRect(x: size.width / 2 - 350, y: 42, width: 700, height: 60)
    fill(box, NSColor(white: 0.13, alpha: 0.97), radius: 14, in: ctx)
    stroke(box, Ink.accent.withAlphaComponent(0.5), radius: 14, width: 1.5, in: ctx)
    fill(CGRect(x: box.minX + 20, y: box.midY - 4, width: 8, height: 8), Ink.accent, radius: 4, in: ctx)
    text(shown, at: CGPoint(x: box.minX + 42, y: box.midY - 7), size: 18, color: Ink.text,
         mono: true, in: ctx)
    ctx.restoreGState()
}

func drawCaption(_ line: String, _ sub: String, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    text(line, at: CGPoint(x: size.width / 2, y: 92), size: 34, color: Ink.text,
         weight: .semibold, align: .centre, in: ctx)
    text(sub, at: CGPoint(x: size.width / 2, y: 56), size: 17, color: Ink.dim,
         align: .centre, in: ctx)
    ctx.restoreGState()
}

// MARK: - The scene

let margin: CGFloat = 26
let deskTop = size.height - 34 - margin
let deskBottom: CGFloat = 130

// Three zones: a wide left, and two stacked on the right. The layout the
// README describes as "browser on the left 60%, terminal top right, notes
// bottom right".
let zoneLeft = CGRect(x: margin, y: deskBottom, width: (size.width - margin * 3) * 0.6,
                      height: deskTop - deskBottom)
let zoneTopRight = CGRect(x: zoneLeft.maxX + margin, y: deskBottom + (deskTop - deskBottom) / 2 + margin / 2,
                          width: size.width - zoneLeft.maxX - margin * 2,
                          height: (deskTop - deskBottom) / 2 - margin / 2)
let zoneBottomRight = CGRect(x: zoneTopRight.minX, y: deskBottom,
                             width: zoneTopRight.width, height: zoneTopRight.height)
let zones = [zoneLeft, zoneTopRight, zoneBottomRight]

let messy = [
    CGRect(x: 150, y: 300, width: 620, height: 380),
    CGRect(x: 430, y: 210, width: 560, height: 330),
    CGRect(x: 300, y: 160, width: 500, height: 300),
]

func frame(at t: Double) -> CGImage {
    let scale: CGFloat = 1
    let ctx = CGContext(data: nil, width: Int(size.width * scale), height: Int(size.height * scale),
                        bitsPerComponent: 8, bytesPerRow: 0,
                        space: CGColorSpaceCreateDeviceRGB(),
                        bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)!
    ctx.scaleBy(x: scale, y: scale)
    ctx.setAllowsAntialiasing(true)

    drawDesk(in: ctx)

    // Beat 1 (0.6-2.4s): the browser is dragged into the left zone.
    let dragOne = phase(t, from: 0.8, to: 2.2)
    // Beat 2 (2.8-3.8s): the terminal is sent to zone 2 with a shortcut.
    let snapTwo = phase(t, from: 3.0, to: 3.7)
    // Beat 3 (4.2-5.2s): notes to zone 3.
    let snapThree = phase(t, from: 4.4, to: 5.1)
    // Beat 4 (6.0-8.0s): the agent says it instead, and nothing moves because
    // it is already there — the point being that both roads lead here.
    let promptIn = phase(t, from: 5.9, to: 6.3)
    let typing = phase(t, from: 6.2, to: 7.4)

    let zonesShown = max(
        phase(t, from: 0.7, to: 1.0) - phase(t, from: 2.1, to: 2.4),
        max(phase(t, from: 2.9, to: 3.1) - phase(t, from: 3.6, to: 3.9),
            phase(t, from: 4.3, to: 4.5) - phase(t, from: 5.0, to: 5.3))
    )
    var lit: Set<Int> = []
    if t >= 0.7 && t < 2.4 { lit = [0] }
    if t >= 2.9 && t < 3.9 { lit = [1] }
    if t >= 4.3 && t < 5.3 { lit = [2] }

    let panes = [
        Pane(title: "Browser", rect: lerp(messy[0], zoneLeft, dragOne), hue: Ink.accent),
        Pane(title: "Terminal", rect: lerp(messy[1], zoneTopRight, snapTwo),
             hue: NSColor(srgbRed: 0.36, green: 0.85, blue: 0.55, alpha: 1)),
        Pane(title: "Notes", rect: lerp(messy[2], zoneBottomRight, snapThree),
             hue: Ink.amber),
    ]
    // Whatever is moving belongs in front.
    var order = [2, 1, 0]
    if t < 2.4 { order = [2, 1, 0] } else if t < 3.9 { order = [2, 0, 1] } else { order = [0, 1, 2] }
    for index in order { draw(panes[index], in: ctx) }
    // Above the windows, exactly where the real overlay sits.
    drawZones(zones, highlighted: lit, alpha: CGFloat(zonesShown), in: ctx)

    // The pointer rides the first window in, then leaves.
    let cursorAlpha = phase(t, from: 0.4, to: 0.7) - phase(t, from: 2.3, to: 2.6)
    let grip = lerp(messy[0], zoneLeft, dragOne)
    drawCursor(at: CGPoint(x: grip.midX, y: grip.midY), alpha: CGFloat(cursorAlpha), in: ctx)

    // The shortcut that did the second and third.
    drawKeys(["⌃", "⌥", "2"], centeredAt: CGPoint(x: size.width / 2, y: 46),
             alpha: CGFloat(phase(t, from: 2.9, to: 3.1) - phase(t, from: 3.5, to: 3.8)), in: ctx)
    drawKeys(["⌃", "⌥", "3"], centeredAt: CGPoint(x: size.width / 2, y: 46),
             alpha: CGFloat(phase(t, from: 4.3, to: 4.5) - phase(t, from: 4.9, to: 5.2)), in: ctx)

    drawPrompt("browser left 60%, terminal top right, notes bottom right",
               progress: typing,
               alpha: CGFloat(promptIn - phase(t, from: 7.9, to: 8.2)), in: ctx)

    drawCaption("Drag it, press it, or just say it.",
                "Plonk — the Mac window manager your agent can drive.",
                alpha: CGFloat(phase(t, from: 8.2, to: 8.6) - phase(t, from: 8.9, to: 9.0)), in: ctx)

    return ctx.makeImage()!
}

// MARK: - Output

let output = CommandLine.arguments.count > 1 ? CommandLine.arguments[1] : "/tmp/plonk-demo"
try? FileManager.default.createDirectory(atPath: output, withIntermediateDirectories: true)

let total = Int(duration * fps)
for index in 0..<total {
    let image = frame(at: Double(index) / fps)
    let rep = NSBitmapImageRep(cgImage: image)
    guard let data = rep.representation(using: .png, properties: [:]) else { continue }
    let name = String(format: "%s/frame-%04d.png", (output as NSString).utf8String!, index)
    try? data.write(to: URL(fileURLWithPath: name))
}
print("wrote \(total) frames to \(output)")
