#!/usr/bin/env swift
// Draws the README's demo animation, frame by frame, and leaves the PNGs for
// ffmpeg to turn into a GIF. Run it through scripts/make-demo.sh.
//
// A rendered animation rather than a screen recording, on purpose: a recording
// of a window manager is mostly other people's apps, it dates the moment any of
// them is redesigned, and it cannot be regenerated by anyone reading this repo.
// This can — it is one file, and every frame is a pure function of time.

import AppKit
import CoreText

// MARK: - Timeline

let fps = 20.0
let duration = 19.8
let size = CGSize(width: 1200, height: 750)

/// 0 at `from`, 1 at `to`, eased so movement starts and stops softly.
func phase(_ t: Double, from: Double, to: Double) -> Double {
    guard to > from else { return t >= to ? 1 : 0 }
    let raw = min(max((t - from) / (to - from), 0), 1)
    return raw < 0.5 ? 4 * raw * raw * raw : 1 - pow(-2 * raw + 2, 3) / 2
}

func lerp(_ a: Double, _ b: Double, _ t: Double) -> Double { a + (b - a) * t }

func lerp(_ a: CGRect, _ b: CGRect, _ t: Double) -> CGRect {
    CGRect(x: lerp(a.minX, b.minX, t), y: lerp(a.minY, b.minY, t),
           width: lerp(a.width, b.width, t), height: lerp(a.height, b.height, t))
}

// MARK: - Palette

/// 0 while the demo is in the dark theme, 1 in the light one. Every colour is
/// a blend of the two, so the theme beat is one number moving rather than a
/// second copy of the drawing code.
var themeBlend = 0.0

func mix(_ dark: NSColor, _ light: NSColor, _ t: Double) -> NSColor {
    guard t > 0 else { return dark }
    let a = dark.usingColorSpace(.sRGB) ?? dark
    let b = light.usingColorSpace(.sRGB) ?? light
    return NSColor(srgbRed: a.redComponent + (b.redComponent - a.redComponent) * t,
                   green: a.greenComponent + (b.greenComponent - a.greenComponent) * t,
                   blue: a.blueComponent + (b.blueComponent - a.blueComponent) * t,
                   alpha: a.alphaComponent + (b.alphaComponent - a.alphaComponent) * t)
}

enum Ink {
    static var desk: NSColor { mix(NSColor(srgbRed: 0.05, green: 0.055, blue: 0.075, alpha: 1),
                                   NSColor(srgbRed: 0.90, green: 0.91, blue: 0.94, alpha: 1), themeBlend) }
    static var deskGlow: NSColor { mix(NSColor(srgbRed: 0.13, green: 0.13, blue: 0.20, alpha: 1),
                                       NSColor(srgbRed: 0.97, green: 0.97, blue: 1.0, alpha: 1), themeBlend) }
    static var bar: NSColor { mix(NSColor(srgbRed: 0.07, green: 0.08, blue: 0.10, alpha: 0.96),
                                  NSColor(srgbRed: 0.99, green: 0.99, blue: 1.0, alpha: 0.96), themeBlend) }
    /// Plonk's own accent, and the warmer end of the gradient it draws with.
    static let accent = NSColor(srgbRed: 0.545, green: 0.486, blue: 0.965, alpha: 1)
    static let warm = NSColor(srgbRed: 0.949, green: 0.475, blue: 0.373, alpha: 1)
    static let amber = NSColor(srgbRed: 1.0, green: 0.72, blue: 0.30, alpha: 1)
    static var chrome: NSColor { mix(NSColor(srgbRed: 0.13, green: 0.145, blue: 0.19, alpha: 1),
                                     NSColor(srgbRed: 0.93, green: 0.935, blue: 0.95, alpha: 1), themeBlend) }
    static var pane: NSColor { mix(NSColor(srgbRed: 0.086, green: 0.098, blue: 0.129, alpha: 1),
                                   NSColor(srgbRed: 1.0, green: 1.0, blue: 1.0, alpha: 1), themeBlend) }
    static var panel: NSColor { mix(NSColor(srgbRed: 0.10, green: 0.11, blue: 0.145, alpha: 0.98),
                                    NSColor(srgbRed: 1.0, green: 1.0, blue: 1.0, alpha: 0.98), themeBlend) }
    static var text: NSColor { mix(NSColor(white: 0.93, alpha: 1), NSColor(white: 0.09, alpha: 1), themeBlend) }
    static var dim: NSColor { mix(NSColor(white: 0.55, alpha: 1), NSColor(white: 0.42, alpha: 1), themeBlend) }
    static var line: NSColor { mix(NSColor(white: 1, alpha: 0.09), NSColor(white: 0, alpha: 0.10), themeBlend) }
    static var body: NSColor { mix(NSColor(white: 1, alpha: 0.13), NSColor(white: 0, alpha: 0.13), themeBlend) }
}

// MARK: - Drawing helpers

func fill(_ rect: CGRect, _ color: NSColor, radius: CGFloat = 0, in ctx: CGContext) {
    ctx.setFillColor(color.cgColor)
    ctx.addPath(CGPath(roundedRect: rect, cornerWidth: radius, cornerHeight: radius, transform: nil))
    ctx.fillPath()
}

func stroke(_ rect: CGRect, _ color: NSColor, radius: CGFloat = 0, width: CGFloat = 1,
            in ctx: CGContext) {
    ctx.setStrokeColor(color.cgColor)
    ctx.setLineWidth(width)
    ctx.addPath(CGPath(roundedRect: rect.insetBy(dx: width / 2, dy: width / 2),
                       cornerWidth: radius, cornerHeight: radius, transform: nil))
    ctx.strokePath()
}

enum Align { case left, centre }

func text(_ string: String, at point: CGPoint, size fontSize: CGFloat, color: NSColor,
          weight: NSFont.Weight = .regular, align: Align = .left,
          mono: Bool = false, in ctx: CGContext) {
    let font = mono
        ? NSFont.monospacedSystemFont(ofSize: fontSize, weight: weight)
        : NSFont.systemFont(ofSize: fontSize, weight: weight)
    let attributed = NSAttributedString(string: string, attributes: [
        .font: font, .foregroundColor: color,
    ])
    let line = CTLineCreateWithAttributedString(attributed)
    var x = point.x
    if align == .centre {
        x -= CTLineGetTypographicBounds(line, nil, nil, nil) / 2
    }
    ctx.textPosition = CGPoint(x: x, y: point.y)
    CTLineDraw(line, ctx)
}

func width(of string: String, size fontSize: CGFloat, weight: NSFont.Weight = .regular,
           mono: Bool = false) -> CGFloat {
    let font = mono
        ? NSFont.monospacedSystemFont(ofSize: fontSize, weight: weight)
        : NSFont.systemFont(ofSize: fontSize, weight: weight)
    let attributed = NSAttributedString(string: string, attributes: [.font: font])
    return CTLineGetTypographicBounds(CTLineCreateWithAttributedString(attributed), nil, nil, nil)
}

// MARK: - Pieces of the picture

/// The desk: a dark screen with a menu bar and Plonk's cube in it.
func drawDesk(in ctx: CGContext) {
    fill(CGRect(origin: .zero, size: size), Ink.desk, in: ctx)
    // A soft pool of light behind everything, so the flat colours have somewhere to sit.
    let glow = CGGradient(colorsSpace: CGColorSpaceCreateDeviceRGB(),
                          colors: [Ink.deskGlow.cgColor, Ink.desk.cgColor] as CFArray,
                          locations: [0, 1])!
    ctx.drawRadialGradient(glow, startCenter: CGPoint(x: size.width / 2, y: size.height * 0.62),
                           startRadius: 0, endCenter: CGPoint(x: size.width / 2, y: size.height * 0.62),
                           endRadius: size.width * 0.62, options: [])

    let bar = CGRect(x: 0, y: size.height - 34, width: size.width, height: 34)
    fill(bar, Ink.bar, in: ctx)
    // The cube, drawn small: two faces and a top, same shape as the status icon.
    let cube = CGRect(x: size.width - 58, y: size.height - 25, width: 16, height: 16)
    fill(CGRect(x: cube.minX, y: cube.minY, width: 16, height: 11), Ink.amber, radius: 2, in: ctx)
    fill(CGRect(x: cube.minX + 3, y: cube.minY + 8, width: 10, height: 6),
         Ink.amber.withAlphaComponent(0.55), radius: 2, in: ctx)
    text("Plonk", at: CGPoint(x: 20, y: size.height - 23), size: 13, color: Ink.dim,
         weight: .semibold, in: ctx)
}

struct Pane {
    var title: String
    var rect: CGRect
    var hue: NSColor
}

/// A window: title bar, three lights, a few lines of content.
///
/// Everything scales with the pane, because in the grid a window is a third of
/// the width it had on the pile: full-size chrome on a small tile reads as a
/// toolbar, and full-size body lines read as static.
func draw(_ pane: Pane, alpha: CGFloat = 1, in ctx: CGContext) {
    let scale = min(max(pane.rect.width / 560, 0.6), 1)
    let radius: CGFloat = 10 * scale + 3
    ctx.saveGState()
    ctx.setAlpha(alpha)
    ctx.setShadow(offset: CGSize(width: 0, height: -6 * scale), blur: 22 * scale,
                  color: NSColor.black.withAlphaComponent(0.55).cgColor)
    fill(pane.rect, Ink.pane, radius: radius, in: ctx)
    ctx.setShadow(offset: .zero, blur: 0, color: nil)
    stroke(pane.rect, Ink.line, radius: radius, in: ctx)

    let chromeHeight = round(30 * scale)
    let chrome = CGRect(x: pane.rect.minX, y: pane.rect.maxY - chromeHeight,
                        width: pane.rect.width, height: chromeHeight)
    ctx.saveGState()
    ctx.addPath(CGPath(roundedRect: pane.rect, cornerWidth: radius, cornerHeight: radius, transform: nil))
    ctx.clip()
    fill(chrome, Ink.chrome, in: ctx)
    ctx.restoreGState()

    let light = 9 * scale
    for (index, colour) in [NSColor(srgbRed: 1, green: 0.37, blue: 0.34, alpha: 1),
                            NSColor(srgbRed: 1, green: 0.74, blue: 0.18, alpha: 1),
                            NSColor(srgbRed: 0.24, green: 0.79, blue: 0.33, alpha: 1)].enumerated() {
        fill(CGRect(x: chrome.minX + 14 * scale + CGFloat(index) * (light + 7 * scale),
                    y: chrome.midY - light / 2, width: light, height: light),
             colour, radius: light / 2, in: ctx)
    }
    let titleSize = max(9, 12 * scale)
    let titleX = chrome.minX + 14 * scale + 3 * (light + 7 * scale) + 14 * scale
    if titleX + width(of: pane.title, size: titleSize, weight: .medium) < chrome.maxX - 10 {
        text(pane.title, at: CGPoint(x: titleX, y: chrome.midY - titleSize * 0.4), size: titleSize,
             color: Ink.dim, weight: .medium, in: ctx)
    }

    // Content: a coloured header rule, then grey lines that fit the width.
    let body = pane.rect.insetBy(dx: 18 * scale, dy: 0)
    var y = chrome.minY - 26 * scale
    fill(CGRect(x: body.minX, y: y, width: min(body.width * 0.42, 150 * scale), height: 7 * scale),
         pane.hue.withAlphaComponent(0.9), radius: 3.5 * scale, in: ctx)
    y -= 20 * scale
    let widths: [CGFloat] = [0.9, 0.66, 0.82, 0.5, 0.74, 0.6, 0.86, 0.44, 0.78]
    var index = 0
    // Filled to the bottom rather than to a fixed count: a window with a third
    // of its content drawn reads as a window that is still loading.
    while y > pane.rect.minY + 18 * scale {
        fill(CGRect(x: body.minX, y: y, width: body.width * widths[index % widths.count],
                    height: 5 * scale),
             Ink.body, radius: 2.5 * scale, in: ctx)
        // A paragraph break every so often, so it reads as text and not a barcode.
        y -= ((index % 5 == 4) ? 26 : 15) * scale
        index += 1
    }
    ctx.restoreGState()
}

/// The zone overlay, as the app draws it: rounded tiles, numbered, one lit.
func drawZones(_ zones: [CGRect], highlighted: Set<Int>, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    for (index, zone) in zones.enumerated() {
        let lit = highlighted.contains(index)
        fill(zone, Ink.accent.withAlphaComponent(lit ? 0.28 : 0.10), radius: 10, in: ctx)
        stroke(zone, Ink.accent.withAlphaComponent(lit ? 0.95 : 0.4), radius: 10,
               width: lit ? 2.5 : 1.5, in: ctx)
        // The number fits the tile: eight zones means some of them are small.
        let numberSize = max(22, min(54, min(zone.width, zone.height) * 0.3))
        text("\(index + 1)", at: CGPoint(x: zone.midX, y: zone.midY - numberSize * 0.37),
             size: numberSize,
             color: Ink.accent.withAlphaComponent(lit ? 0.95 : 0.38), weight: .bold,
             align: .centre, in: ctx)
    }
    ctx.restoreGState()
}

/// A row of key caps, e.g. ⌃⌥2.
func drawKeys(_ keys: [String], centeredAt point: CGPoint, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    let capHeight: CGFloat = 46
    let caps = keys.map { max(capHeight, width(of: $0, size: 22, weight: .semibold) + 26) }
    let total = caps.reduce(0, +) + CGFloat(keys.count - 1) * 8
    var x = point.x - total / 2
    for (index, key) in keys.enumerated() {
        let rect = CGRect(x: x, y: point.y, width: caps[index], height: capHeight)
        fill(rect, NSColor(white: 0.16, alpha: 0.96), radius: 9, in: ctx)
        stroke(rect, NSColor(white: 1, alpha: 0.16), radius: 9, in: ctx)
        text(key, at: CGPoint(x: rect.midX, y: rect.midY - 9), size: 22, color: Ink.text,
             weight: .semibold, align: .centre, in: ctx)
        x += caps[index] + 8
    }
    ctx.restoreGState()
}

/// The pointer, drawn rather than screenshotted so it renders at any size.
func drawCursor(at point: CGPoint, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    ctx.setShadow(offset: CGSize(width: 0, height: -2), blur: 6,
                  color: NSColor.black.withAlphaComponent(0.6).cgColor)
    let path = CGMutablePath()
    path.move(to: point)
    path.addLine(to: CGPoint(x: point.x, y: point.y - 26))
    path.addLine(to: CGPoint(x: point.x + 6.5, y: point.y - 19.5))
    path.addLine(to: CGPoint(x: point.x + 11, y: point.y - 28))
    path.addLine(to: CGPoint(x: point.x + 16, y: point.y - 25.5))
    path.addLine(to: CGPoint(x: point.x + 11.5, y: point.y - 17))
    path.addLine(to: CGPoint(x: point.x + 20, y: point.y - 16))
    path.closeSubpath()
    ctx.addPath(path)
    ctx.setFillColor(NSColor.white.cgColor)
    ctx.fillPath()
    ctx.restoreGState()
}

/// The agent's line, typed out a character at a time.
func drawPrompt(_ line: String, progress: Double, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    let shown = String(line.prefix(Int(Double(line.count) * min(max(progress, 0), 1))))
    let box = CGRect(x: size.width / 2 - 350, y: 42, width: 700, height: 60)
    fill(box, NSColor(white: 0.13, alpha: 0.97), radius: 14, in: ctx)
    stroke(box, Ink.accent.withAlphaComponent(0.5), radius: 14, width: 1.5, in: ctx)
    fill(CGRect(x: box.minX + 20, y: box.midY - 4, width: 8, height: 8), Ink.accent, radius: 4, in: ctx)
    text(shown, at: CGPoint(x: box.minX + 42, y: box.midY - 7), size: 18, color: Ink.text,
         mono: true, in: ctx)
    ctx.restoreGState()
}

func drawCaption(_ line: String, _ sub: String, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    text(line, at: CGPoint(x: size.width / 2, y: 92), size: 34, color: Ink.text,
         weight: .semibold, align: .centre, in: ctx)
    text(sub, at: CGPoint(x: size.width / 2, y: 56), size: 17, color: Ink.dim,
         align: .centre, in: ctx)
    ctx.restoreGState()
}

// MARK: - The scene

let margin: CGFloat = 22
let deskTop = size.height - 34 - margin
let deskBottom: CGFloat = 128
let desk = CGRect(x: margin, y: deskBottom, width: size.width - margin * 2, height: deskTop - deskBottom)

/// A zone as the app stores one: a fraction of the screen, origin top-left.
struct Frac {
    var x: Double, y: Double, w: Double, h: Double

    var rect: CGRect {
        CGRect(x: desk.minX + desk.width * x, y: desk.maxY - desk.height * (y + h),
               width: desk.width * w, height: desk.height * h)
    }

    func contains(_ px: Double, _ py: Double) -> Bool {
        px > x && px < x + w && py > y && py < y + h
    }
}

/// One click in the zone editor: where the pointer is, and whether ⇧ is down.
/// A plain click cuts across, ⇧ cuts down the way — the same two the editor
/// has, at the same place the pointer is, on the same 0.05 grid it snaps to.
struct Split {
    var at: Double
    var x: Double
    var y: Double
    var vertical: Bool
}

// Seven clicks turn one full-screen zone into the eight the rest of the demo
// uses. Written as clicks rather than as eight rectangles so the layout cannot
// drift into one the editor could not actually produce.
let splits = [
    Split(at: 0.75, x: 0.25, y: 0.45, vertical: true),
    Split(at: 1.15, x: 0.70, y: 0.40, vertical: true),
    Split(at: 1.53, x: 0.12, y: 0.55, vertical: false),
    Split(at: 1.91, x: 0.45, y: 0.70, vertical: false),
    Split(at: 2.29, x: 0.50, y: 0.85, vertical: true),
    Split(at: 2.67, x: 0.85, y: 0.35, vertical: false),
    Split(at: 3.05, x: 0.85, y: 0.65, vertical: false),
]
let splitTime = 0.22

/// Every state the draft passes through, plus the parent and the two children
/// of each split, which is what the animation needs.
struct Stage {
    var zones: [Frac]
    var parent: Frac
    var first: Frac
    var second: Frac
}

let stages: [Stage] = {
    var zones = [Frac(x: 0, y: 0, w: 1, h: 1)]
    var result: [Stage] = []
    for split in splits {
        guard let index = zones.firstIndex(where: { $0.contains(split.x, split.y) }) else { continue }
        let parent = zones[index]
        let first: Frac, second: Frac
        if split.vertical {
            let cut = split.x - parent.x
            first = Frac(x: parent.x, y: parent.y, w: cut, h: parent.h)
            second = Frac(x: split.x, y: parent.y, w: parent.w - cut, h: parent.h)
        } else {
            let cut = split.y - parent.y
            first = Frac(x: parent.x, y: parent.y, w: parent.w, h: cut)
            second = Frac(x: parent.x, y: split.y, w: parent.w, h: parent.h - cut)
        }
        zones.replaceSubrange(index...index, with: [first, second])
        result.append(Stage(zones: zones, parent: parent, first: first, second: second))
    }
    return result
}()

let zones = stages.last!.zones.map(\.rect)

/// The draft as it stands at `t`, with the split in progress half-done.
func draftZones(at t: Double) -> [CGRect] {
    guard let index = splits.lastIndex(where: { t >= $0.at }) else {
        return [Frac(x: 0, y: 0, w: 1, h: 1).rect]
    }
    let stage = stages[index]
    let progress = phase(t, from: splits[index].at, to: splits[index].at + splitTime)
    guard progress < 1 else { return stage.zones.map(\.rect) }

    // The half that keeps the origin shrinks into place; the other half grows
    // out of the line the click drew, which is what a split looks like.
    let sliver = splits[index].vertical
        ? Frac(x: stage.second.x, y: stage.second.y, w: 0.001, h: stage.second.h)
        : Frac(x: stage.second.x, y: stage.second.y, w: stage.second.w, h: 0.001)
    return stage.zones.map { zone in
        if zone.x == stage.first.x && zone.y == stage.first.y && zone.w == stage.first.w {
            return lerp(stage.parent.rect, stage.first.rect, progress)
        }
        if zone.x == stage.second.x && zone.y == stage.second.y {
            return lerp(sliver.rect, stage.second.rect, progress)
        }
        return zone.rect
    }
}

/// The editor: the screen dimmed, the draft on top, and the panel that names
/// the set and says what a click does.
func drawEditor(at t: Double, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    fill(CGRect(origin: .zero, size: size), NSColor.black.withAlphaComponent(0.42), in: ctx)
    for zone in draftZones(at: t) {
        fill(zone.insetBy(dx: 2, dy: 2), Ink.accent.withAlphaComponent(0.13), radius: 8, in: ctx)
        stroke(zone.insetBy(dx: 2, dy: 2), Ink.accent.withAlphaComponent(0.75), radius: 8,
               width: 2, in: ctx)
    }

    let panel = CGRect(x: size.width / 2 - 250, y: 30, width: 500, height: 78)
    fill(panel, NSColor(white: 0.15, alpha: 0.97), radius: 12, in: ctx)
    stroke(panel, NSColor(white: 1, alpha: 0.14), radius: 12, in: ctx)
    text("Demo Grid", at: CGPoint(x: panel.minX + 20, y: panel.maxY - 30), size: 16,
         color: Ink.text, weight: .semibold, in: ctx)
    text("Click a zone to split it — hold ⇧ for a vertical split", at: CGPoint(x: panel.minX + 20, y: panel.minY + 20),
         size: 13, color: Ink.dim, in: ctx)
    let save = CGRect(x: panel.maxX - 130, y: panel.midY - 15, width: 110, height: 30)
    fill(save, Ink.accent.withAlphaComponent(0.9), radius: 8, in: ctx)
    text("Save & Apply", at: CGPoint(x: save.midX, y: save.midY - 5), size: 12.5,
         color: NSColor(white: 0.08, alpha: 1), weight: .semibold, align: .centre, in: ctx)
    ctx.restoreGState()
}

/// The ring a click leaves, so seven fast clicks read as seven clicks.
func drawClick(at point: CGPoint, progress: Double, in ctx: CGContext) {
    guard progress > 0, progress < 1 else { return }
    ctx.saveGState()
    ctx.setAlpha(CGFloat(1 - progress))
    stroke(CGRect(x: point.x - 26 * progress, y: point.y - 26 * progress,
                  width: 52 * progress, height: 52 * progress),
           Ink.accent, radius: 26 * progress, width: 2.5, in: ctx)
    ctx.restoreGState()
}

/// Where the pointer is during the editor beat: at the next click, having
/// travelled there from the last one.
func editorCursor(at t: Double) -> (point: CGPoint, shift: Bool) {
    var previous = CGPoint(x: desk.midX, y: desk.midY)
    for (index, split) in splits.enumerated() {
        let target = CGPoint(x: desk.minX + desk.width * split.x,
                             y: desk.maxY - desk.height * split.y)
        if t < split.at {
            let start = index == 0 ? 0.35 : splits[index - 1].at + splitTime
            let travel = phase(t, from: start, to: split.at)
            return (CGPoint(x: lerp(previous.x, target.x, travel),
                            y: lerp(previous.y, target.y, travel)), split.vertical)
        }
        previous = target
    }
    return (previous, false)
}

/// The ⇧ badge that rides the pointer when the next click is a vertical split.
func drawShiftBadge(at point: CGPoint, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    let badge = CGRect(x: point.x + 22, y: point.y - 44, width: 30, height: 28)
    fill(badge, NSColor(white: 0.16, alpha: 0.96), radius: 7, in: ctx)
    stroke(badge, NSColor(white: 1, alpha: 0.2), radius: 7, in: ctx)
    text("⇧", at: CGPoint(x: badge.midX, y: badge.midY - 7), size: 15, color: Ink.text,
         weight: .semibold, align: .centre, in: ctx)
    ctx.restoreGState()
}

/// The set the palette switches to: one big zone and three down the side. The
/// switch is a real Plonk feature — windows sitting in a numbered zone move to
/// wherever that number is in the new set — so the animation is just the same
/// windows easing to a different rectangle.
let focusFracs = [
    Frac(x: 0, y: 0, w: 0.62, h: 1),
    Frac(x: 0.62, y: 0, w: 0.38, h: 0.34),
    Frac(x: 0.62, y: 0.34, w: 0.38, h: 0.33),
    Frac(x: 0.62, y: 0.67, w: 0.38, h: 0.33),
]

/// ⌘K, drawn the way the app draws it: a field, a few matching commands, the
/// first one selected.
func drawPalette(_ query: String, rows: [(String, [String])], selected: Int,
                 typed: Double, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    let rowHeight: CGFloat = 34
    let height = 58 + CGFloat(rows.count) * rowHeight + 30
    let box = CGRect(x: size.width / 2 - 290, y: size.height - 250 - height, width: 580, height: height)
    ctx.setShadow(offset: CGSize(width: 0, height: -10), blur: 40,
                  color: NSColor.black.withAlphaComponent(0.55).cgColor)
    fill(box, Ink.panel, radius: 14, in: ctx)
    ctx.setShadow(offset: .zero, blur: 0, color: nil)
    stroke(box, Ink.line, radius: 14, width: 1, in: ctx)

    let shown = String(query.prefix(Int(Double(query.count) * min(max(typed, 0), 1))))
    text(shown, at: CGPoint(x: box.minX + 46, y: box.maxY - 36), size: 16, color: Ink.text, in: ctx)
    // The caret, and the magnifier drawn as a circle with a tail.
    let caretX = box.minX + 46 + width(of: shown, size: 16) + 2
    fill(CGRect(x: caretX, y: box.maxY - 40, width: 1.5, height: 18), Ink.accent, in: ctx)
    stroke(CGRect(x: box.minX + 20, y: box.maxY - 37, width: 13, height: 13), Ink.dim,
           radius: 6.5, width: 1.4, in: ctx)
    fill(CGRect(x: box.minX + 30, y: box.maxY - 42, width: 6, height: 1.4), Ink.dim, in: ctx)
    fill(CGRect(x: box.minX, y: box.maxY - 58, width: box.width, height: 1), Ink.line, in: ctx)

    for (index, row) in rows.enumerated() {
        let top = box.maxY - 58 - CGFloat(index + 1) * rowHeight
        let rect = CGRect(x: box.minX, y: top, width: box.width, height: rowHeight)
        if index == selected {
            fill(rect, Ink.accent.withAlphaComponent(0.16), in: ctx)
            fill(CGRect(x: rect.minX, y: rect.minY, width: 2.5, height: rect.height), Ink.accent, in: ctx)
        }
        text(row.0, at: CGPoint(x: rect.minX + 20, y: rect.midY - 5), size: 13.5,
             color: index == selected ? Ink.text : Ink.dim, in: ctx)
        var x = rect.maxX - 20
        for key in row.1.reversed() {
            let capWidth = max(22, width(of: key, size: 11, weight: .medium) + 12)
            let cap = CGRect(x: x - capWidth, y: rect.midY - 9, width: capWidth, height: 18)
            fill(cap, Ink.body, radius: 4, in: ctx)
            text(key, at: CGPoint(x: cap.midX, y: cap.midY - 4), size: 11, color: Ink.dim,
                 weight: .medium, align: .centre, in: ctx)
            x -= capWidth + 4
        }
    }
    fill(CGRect(x: box.minX, y: box.minY + 30, width: box.width, height: 1), Ink.line, in: ctx)
    text("Anything an agent can do, you can type",
         at: CGPoint(x: box.midX, y: box.minY + 11), size: 11, color: Ink.dim, align: .centre, in: ctx)
    ctx.restoreGState()
}

/// The theme switch from the sidebar footer, shown on its own while the whole
/// picture changes behind it.
func drawThemeSwitch(progress: Double, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    let box = CGRect(x: size.width / 2 - 60, y: 150, width: 120, height: 40)
    fill(box, Ink.panel, radius: 11, in: ctx)
    stroke(box, Ink.line, radius: 11, width: 1, in: ctx)
    let cell = (box.width - 8) / 3
    // Glyphs are system, sun, moon: dark is the moon, light is the sun.
    let index = progress < 0.5 ? 2.0 : 1.0
    let knob = CGRect(x: box.minX + 4 + cell * index, y: box.minY + 4, width: cell, height: box.height - 8)
    fill(knob, Ink.accent.withAlphaComponent(0.9), radius: 8, in: ctx)
    for (slot, glyph) in ["A", "\u{2600}", "\u{263D}"].enumerated() {
        let centre = CGPoint(x: box.minX + 4 + cell * (Double(slot) + 0.5), y: box.midY - 7)
        text(glyph, at: centre, size: 15,
             color: Double(slot) == index ? .white : Ink.dim, weight: .semibold, align: .centre, in: ctx)
    }
    ctx.restoreGState()
}

/// One window: where it starts on the pile, where it belongs, and when it goes.
struct Window {
    var title: String
    var hue: NSColor
    var messy: CGRect
    var home: CGRect
    var from: Double
    var to: Double
}

let green = NSColor(srgbRed: 0.36, green: 0.85, blue: 0.55, alpha: 1)
let violet = NSColor(srgbRed: 0.68, green: 0.55, blue: 1.0, alpha: 1)
let pink = NSColor(srgbRed: 1.0, green: 0.45, blue: 0.62, alpha: 1)
let teal = NSColor(srgbRed: 0.30, green: 0.80, blue: 0.82, alpha: 1)

// The pile: eight windows, cascaded and overlapping, a few running off the
// edges. It is the state the app exists to end, so it is worth drawing badly
// on purpose. Zone order is the order the splits made them in.
let windows = [
    // Dragged by hand, once the grid exists.
    Window(title: "Browser", hue: Ink.accent,
           messy: CGRect(x: 96, y: 286, width: 560, height: 360), home: zones[0],
           from: 4.1, to: 5.2),
    // Sent with a shortcut.
    Window(title: "Editor", hue: violet,
           messy: CGRect(x: 372, y: 214, width: 620, height: 400), home: zones[2],
           from: 5.7, to: 6.3),
    // The remaining six, all at once, when the sentence lands.
    Window(title: "Files", hue: teal,
           messy: CGRect(x: 58, y: 168, width: 430, height: 270), home: zones[1],
           from: 8.2, to: 8.95),
    Window(title: "Terminal", hue: green,
           messy: CGRect(x: 610, y: 150, width: 500, height: 300), home: zones[3],
           from: 8.3, to: 9.05),
    Window(title: "Tests", hue: Ink.amber,
           messy: CGRect(x: 264, y: 132, width: 470, height: 290), home: zones[4],
           from: 8.4, to: 9.15),
    Window(title: "Logs", hue: pink,
           messy: CGRect(x: 786, y: 330, width: 460, height: 300), home: zones[5],
           from: 8.5, to: 9.25),
    Window(title: "Chat", hue: Ink.accent,
           messy: CGRect(x: 148, y: 384, width: 400, height: 300), home: zones[6],
           from: 8.6, to: 9.35),
    Window(title: "Mail", hue: green,
           messy: CGRect(x: 500, y: 400, width: 520, height: 290), home: zones[7],
           from: 8.7, to: 9.45),
]

func frame(at t: Double) -> CGImage {
    let scale: CGFloat = 1
    let ctx = CGContext(data: nil, width: Int(size.width * scale), height: Int(size.height * scale),
                        bitsPerComponent: 8, bytesPerRow: 0,
                        space: CGColorSpaceCreateDeviceRGB(),
                        bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)!
    ctx.scaleBy(x: scale, y: scale)
    ctx.setAllowsAntialiasing(true)

    // Beat 6 (14.9-15.9s): the theme changes under everything already drawn.
    themeBlend = phase(t, from: 14.9, to: 15.9)

    drawDesk(in: ctx)

    // Beat 1 (0.3-3.7s): the grid gets drawn, seven clicks, over the mess it
    // is about to sort out. Without it the layout looks like something that
    // shipped in the app rather than something you make in a few seconds.
    let editor = phase(t, from: 0.3, to: 0.55) - phase(t, from: 3.45, to: 3.75)
    // Beat 2 (4.0-5.4s): one window dragged into its zone, by hand.
    // Beat 3 (5.6-6.5s): the next one sent there with a shortcut.
    // Beat 4 (6.7-9.5s): a sentence, and the other six go at once.
    let promptIn = phase(t, from: 6.7, to: 6.95)
    let typing = phase(t, from: 7.0, to: 8.2)

    // The overlay is drawn only while a window is being placed by hand or by
    // key, which is when the app actually draws it.
    let zonesShown = max(phase(t, from: 3.95, to: 4.15) - phase(t, from: 5.2, to: 5.45),
                         phase(t, from: 5.55, to: 5.7) - phase(t, from: 6.3, to: 6.55))
    var lit: Set<Int> = []
    if t >= 3.95 && t < 5.45 { lit = [0] }
    if t >= 5.55 && t < 6.55 { lit = [2] }

    // Beat 5 (10.0-13.1s): ⌘K, and the whole screen re-flows into another zone
    // set. Windows sitting in a numbered zone move to wherever that number is
    // in the new one, which is exactly what the app does.
    let paletteIn = phase(t, from: 11.0, to: 11.25) - phase(t, from: 13.0, to: 13.2)
    let switching = phase(t, from: 13.1, to: 14.4)

    // Each window sits on the pile until its moment, then eases home; then the
    // zone set changes and it eases again. Four zones and eight windows, so the
    // second four stack behind the first four, offset the way the app offsets
    // windows that share a zone.
    let placed = windows.map { phase(t, from: $0.from, to: $0.to) }
    let panes = windows.enumerated().map { index, window -> Pane in
        var rect = lerp(window.messy, window.home, placed[index])
        if switching > 0 {
            let step = CGFloat(index / focusFracs.count) * 14
            let target = focusFracs[index % focusFracs.count].rect
                .offsetBy(dx: step, dy: -step)
                .insetBy(dx: step / 2, dy: step / 2)
            rect = lerp(rect, target, switching)
        }
        return Pane(title: window.title, rect: rect, hue: window.hue)
    }
    // Back to front: the untouched pile, then what has landed, then whatever is
    // in flight — a moving window is the one you are meant to be watching. Once
    // the sets swap, the stacked copies go behind the four that own a zone.
    let order = panes.indices.sorted { a, b in
        func layer(_ index: Int) -> Int {
            if switching > 0.01 { return index < focusFracs.count ? 1 : 0 }
            if placed[index] <= 0 { return 0 }
            return placed[index] >= 1 ? 1 : 2
        }
        return layer(a) == layer(b) ? a > b : layer(a) < layer(b)
    }
    for index in order { draw(panes[index], in: ctx) }

    drawEditor(at: t, alpha: CGFloat(editor), in: ctx)
    // Above the windows, exactly where the real overlay sits.
    drawZones(zones, highlighted: lit, alpha: CGFloat(zonesShown), in: ctx)
    // And once more over the new set, so the switch reads as a set and not as
    // eight windows deciding to move.
    drawZones(focusFracs.map(\.rect), highlighted: [],
              alpha: CGFloat(phase(t, from: 13.1, to: 13.3) - phase(t, from: 14.2, to: 14.5)),
              in: ctx)

    // The pointer: clicking out the grid first, then dragging the first window.
    if editor > 0.01 {
        let (point, shift) = editorCursor(at: t)
        for split in splits {
            drawClick(at: CGPoint(x: desk.minX + desk.width * split.x,
                                  y: desk.maxY - desk.height * split.y),
                      progress: phase(t, from: split.at, to: split.at + 0.3), in: ctx)
        }
        drawShiftBadge(at: point, alpha: CGFloat(editor) * (shift ? 1 : 0), in: ctx)
        drawCursor(at: point, alpha: CGFloat(editor), in: ctx)
    }
    let dragCursor = phase(t, from: 3.8, to: 4.0) - phase(t, from: 5.3, to: 5.5)
    let grip = panes[0].rect
    drawCursor(at: CGPoint(x: grip.midX, y: grip.midY), alpha: CGFloat(dragCursor), in: ctx)

    // The shortcut that placed the second one: zone 3 is the editor's tile.
    drawKeys(["⌃", "⌥", "3"], centeredAt: CGPoint(x: size.width / 2, y: 44),
             alpha: CGFloat(phase(t, from: 5.55, to: 5.7) - phase(t, from: 6.3, to: 6.55)), in: ctx)

    drawPrompt("and the rest into the grid — logs and chat on the right",
               progress: typing,
               alpha: CGFloat(promptIn - phase(t, from: 9.5, to: 9.75)), in: ctx)

    drawPalette("zone set focus",
                rows: [("Use zone set \u{201C}Focus\u{201D} on this screen", ["\u{2318}", "\u{21A9}"]),
                       ("Edit zone sets\u{2026}", []),
                       ("Launch workspace \u{201C}Deep work\u{201D}", ["\u{2303}", "\u{2325}", "W"])],
                selected: 0,
                typed: phase(t, from: 11.35, to: 12.5),
                alpha: CGFloat(paletteIn), in: ctx)

    // Beat 6: the switch itself, held on screen while the colours change.
    drawThemeSwitch(progress: themeBlend,
                    alpha: CGFloat(phase(t, from: 14.6, to: 14.85) - phase(t, from: 16.3, to: 16.55)),
                    in: ctx)

    drawCaption("Draw the grid once. Fill it in a sentence.",
                "Every window, from the keyboard \u{00B7} the menu bar \u{00B7} or an agent.",
                alpha: CGFloat(phase(t, from: 9.6, to: 9.95) - phase(t, from: 10.6, to: 10.85)),
                in: ctx)
    drawCaption("\u{2318}K runs anything. Light or dark, everywhere.",
                "Plonk \u{2014} the Mac window manager your agent can drive.",
                alpha: CGFloat(phase(t, from: 16.8, to: 17.2) - phase(t, from: 19.6, to: 19.8)),
                in: ctx)

    return ctx.makeImage()!
}

// MARK: - Output

let output = CommandLine.arguments.count > 1 ? CommandLine.arguments[1] : "/tmp/plonk-demo"
try? FileManager.default.createDirectory(atPath: output, withIntermediateDirectories: true)

let total = Int(duration * fps)
for index in 0..<total {
    let image = frame(at: Double(index) / fps)
    let rep = NSBitmapImageRep(cgImage: image)
    guard let data = rep.representation(using: .png, properties: [:]) else { continue }
    let name = String(format: "%s/frame-%04d.png", (output as NSString).utf8String!, index)
    try? data.write(to: URL(fileURLWithPath: name))
}
print("wrote \(total) frames to \(output)")
