#!/usr/bin/env swift
// Draws the README's demo animation, frame by frame, and leaves the PNGs for
// ffmpeg to turn into a GIF. Run it through scripts/make-demo.sh.
//
// A rendered animation rather than a screen recording, on purpose: a recording
// of a window manager is mostly other people's apps, it dates the moment any of
// them is redesigned, and it cannot be regenerated by anyone reading this repo.
// This can — it is one file, and every frame is a pure function of time.

import AppKit
import CoreText

// MARK: - Timeline

let fps = 20.0
let duration = 10.5
let size = CGSize(width: 1200, height: 750)

/// 0 at `from`, 1 at `to`, eased so movement starts and stops softly.
func phase(_ t: Double, from: Double, to: Double) -> Double {
    guard to > from else { return t >= to ? 1 : 0 }
    let raw = min(max((t - from) / (to - from), 0), 1)
    return raw < 0.5 ? 4 * raw * raw * raw : 1 - pow(-2 * raw + 2, 3) / 2
}

func lerp(_ a: Double, _ b: Double, _ t: Double) -> Double { a + (b - a) * t }

func lerp(_ a: CGRect, _ b: CGRect, _ t: Double) -> CGRect {
    CGRect(x: lerp(a.minX, b.minX, t), y: lerp(a.minY, b.minY, t),
           width: lerp(a.width, b.width, t), height: lerp(a.height, b.height, t))
}

// MARK: - Palette

enum Ink {
    static let desk = NSColor(srgbRed: 0.07, green: 0.08, blue: 0.11, alpha: 1)
    static let deskGlow = NSColor(srgbRed: 0.13, green: 0.15, blue: 0.22, alpha: 1)
    static let bar = NSColor(srgbRed: 0.10, green: 0.11, blue: 0.15, alpha: 0.96)
    static let accent = NSColor(srgbRed: 0.35, green: 0.62, blue: 1.0, alpha: 1)
    static let amber = NSColor(srgbRed: 1.0, green: 0.72, blue: 0.30, alpha: 1)
    static let chrome = NSColor(srgbRed: 0.17, green: 0.19, blue: 0.24, alpha: 1)
    static let pane = NSColor(srgbRed: 0.12, green: 0.13, blue: 0.17, alpha: 1)
    static let text = NSColor(white: 0.92, alpha: 1)
    static let dim = NSColor(white: 0.55, alpha: 1)
}

// MARK: - Drawing helpers

func fill(_ rect: CGRect, _ color: NSColor, radius: CGFloat = 0, in ctx: CGContext) {
    ctx.setFillColor(color.cgColor)
    ctx.addPath(CGPath(roundedRect: rect, cornerWidth: radius, cornerHeight: radius, transform: nil))
    ctx.fillPath()
}

func stroke(_ rect: CGRect, _ color: NSColor, radius: CGFloat = 0, width: CGFloat = 1,
            in ctx: CGContext) {
    ctx.setStrokeColor(color.cgColor)
    ctx.setLineWidth(width)
    ctx.addPath(CGPath(roundedRect: rect.insetBy(dx: width / 2, dy: width / 2),
                       cornerWidth: radius, cornerHeight: radius, transform: nil))
    ctx.strokePath()
}

enum Align { case left, centre }

func text(_ string: String, at point: CGPoint, size fontSize: CGFloat, color: NSColor,
          weight: NSFont.Weight = .regular, align: Align = .left,
          mono: Bool = false, in ctx: CGContext) {
    let font = mono
        ? NSFont.monospacedSystemFont(ofSize: fontSize, weight: weight)
        : NSFont.systemFont(ofSize: fontSize, weight: weight)
    let attributed = NSAttributedString(string: string, attributes: [
        .font: font, .foregroundColor: color,
    ])
    let line = CTLineCreateWithAttributedString(attributed)
    var x = point.x
    if align == .centre {
        x -= CTLineGetTypographicBounds(line, nil, nil, nil) / 2
    }
    ctx.textPosition = CGPoint(x: x, y: point.y)
    CTLineDraw(line, ctx)
}

func width(of string: String, size fontSize: CGFloat, weight: NSFont.Weight = .regular,
           mono: Bool = false) -> CGFloat {
    let font = mono
        ? NSFont.monospacedSystemFont(ofSize: fontSize, weight: weight)
        : NSFont.systemFont(ofSize: fontSize, weight: weight)
    let attributed = NSAttributedString(string: string, attributes: [.font: font])
    return CTLineGetTypographicBounds(CTLineCreateWithAttributedString(attributed), nil, nil, nil)
}

// MARK: - Pieces of the picture

/// The desk: a dark screen with a menu bar and Plonk's cube in it.
func drawDesk(in ctx: CGContext) {
    fill(CGRect(origin: .zero, size: size), Ink.desk, in: ctx)
    // A soft pool of light behind everything, so the flat colours have somewhere to sit.
    let glow = CGGradient(colorsSpace: CGColorSpaceCreateDeviceRGB(),
                          colors: [Ink.deskGlow.cgColor, Ink.desk.cgColor] as CFArray,
                          locations: [0, 1])!
    ctx.drawRadialGradient(glow, startCenter: CGPoint(x: size.width / 2, y: size.height * 0.62),
                           startRadius: 0, endCenter: CGPoint(x: size.width / 2, y: size.height * 0.62),
                           endRadius: size.width * 0.62, options: [])

    let bar = CGRect(x: 0, y: size.height - 34, width: size.width, height: 34)
    fill(bar, Ink.bar, in: ctx)
    // The cube, drawn small: two faces and a top, same shape as the status icon.
    let cube = CGRect(x: size.width - 58, y: size.height - 25, width: 16, height: 16)
    fill(CGRect(x: cube.minX, y: cube.minY, width: 16, height: 11), Ink.amber, radius: 2, in: ctx)
    fill(CGRect(x: cube.minX + 3, y: cube.minY + 8, width: 10, height: 6),
         Ink.amber.withAlphaComponent(0.55), radius: 2, in: ctx)
    text("Plonk", at: CGPoint(x: 20, y: size.height - 23), size: 13, color: Ink.dim,
         weight: .semibold, in: ctx)
}

struct Pane {
    var title: String
    var rect: CGRect
    var hue: NSColor
}

/// A window: title bar, three lights, a few lines of content.
///
/// Everything scales with the pane, because in the grid a window is a third of
/// the width it had on the pile: full-size chrome on a small tile reads as a
/// toolbar, and full-size body lines read as static.
func draw(_ pane: Pane, alpha: CGFloat = 1, in ctx: CGContext) {
    let scale = min(max(pane.rect.width / 560, 0.6), 1)
    let radius: CGFloat = 10 * scale + 3
    ctx.saveGState()
    ctx.setAlpha(alpha)
    ctx.setShadow(offset: CGSize(width: 0, height: -6 * scale), blur: 22 * scale,
                  color: NSColor.black.withAlphaComponent(0.55).cgColor)
    fill(pane.rect, Ink.pane, radius: radius, in: ctx)
    ctx.setShadow(offset: .zero, blur: 0, color: nil)
    stroke(pane.rect, NSColor(white: 1, alpha: 0.09), radius: radius, in: ctx)

    let chromeHeight = round(30 * scale)
    let chrome = CGRect(x: pane.rect.minX, y: pane.rect.maxY - chromeHeight,
                        width: pane.rect.width, height: chromeHeight)
    ctx.saveGState()
    ctx.addPath(CGPath(roundedRect: pane.rect, cornerWidth: radius, cornerHeight: radius, transform: nil))
    ctx.clip()
    fill(chrome, Ink.chrome, in: ctx)
    ctx.restoreGState()

    let light = 9 * scale
    for (index, colour) in [NSColor(srgbRed: 1, green: 0.37, blue: 0.34, alpha: 1),
                            NSColor(srgbRed: 1, green: 0.74, blue: 0.18, alpha: 1),
                            NSColor(srgbRed: 0.24, green: 0.79, blue: 0.33, alpha: 1)].enumerated() {
        fill(CGRect(x: chrome.minX + 14 * scale + CGFloat(index) * (light + 7 * scale),
                    y: chrome.midY - light / 2, width: light, height: light),
             colour, radius: light / 2, in: ctx)
    }
    let titleSize = max(9, 12 * scale)
    let titleX = chrome.minX + 14 * scale + 3 * (light + 7 * scale) + 14 * scale
    if titleX + width(of: pane.title, size: titleSize, weight: .medium) < chrome.maxX - 10 {
        text(pane.title, at: CGPoint(x: titleX, y: chrome.midY - titleSize * 0.4), size: titleSize,
             color: Ink.dim, weight: .medium, in: ctx)
    }

    // Content: a coloured header rule, then grey lines that fit the width.
    let body = pane.rect.insetBy(dx: 18 * scale, dy: 0)
    var y = chrome.minY - 26 * scale
    fill(CGRect(x: body.minX, y: y, width: min(body.width * 0.42, 150 * scale), height: 7 * scale),
         pane.hue.withAlphaComponent(0.9), radius: 3.5 * scale, in: ctx)
    y -= 20 * scale
    let widths: [CGFloat] = [0.9, 0.66, 0.82, 0.5, 0.74, 0.6, 0.86, 0.44, 0.78]
    var index = 0
    // Filled to the bottom rather than to a fixed count: a window with a third
    // of its content drawn reads as a window that is still loading.
    while y > pane.rect.minY + 18 * scale {
        fill(CGRect(x: body.minX, y: y, width: body.width * widths[index % widths.count],
                    height: 5 * scale),
             NSColor(white: 1, alpha: 0.13), radius: 2.5 * scale, in: ctx)
        // A paragraph break every so often, so it reads as text and not a barcode.
        y -= ((index % 5 == 4) ? 26 : 15) * scale
        index += 1
    }
    ctx.restoreGState()
}

/// The zone overlay, as the app draws it: rounded tiles, numbered, one lit.
func drawZones(_ zones: [CGRect], highlighted: Set<Int>, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    for (index, zone) in zones.enumerated() {
        let lit = highlighted.contains(index)
        fill(zone, Ink.accent.withAlphaComponent(lit ? 0.28 : 0.10), radius: 10, in: ctx)
        stroke(zone, Ink.accent.withAlphaComponent(lit ? 0.95 : 0.4), radius: 10,
               width: lit ? 2.5 : 1.5, in: ctx)
        // The number fits the tile: eight zones means some of them are small.
        let numberSize = max(22, min(54, min(zone.width, zone.height) * 0.3))
        text("\(index + 1)", at: CGPoint(x: zone.midX, y: zone.midY - numberSize * 0.37),
             size: numberSize,
             color: Ink.accent.withAlphaComponent(lit ? 0.95 : 0.38), weight: .bold,
             align: .centre, in: ctx)
    }
    ctx.restoreGState()
}

/// A row of key caps, e.g. ⌃⌥2.
func drawKeys(_ keys: [String], centeredAt point: CGPoint, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    let capHeight: CGFloat = 46
    let caps = keys.map { max(capHeight, width(of: $0, size: 22, weight: .semibold) + 26) }
    let total = caps.reduce(0, +) + CGFloat(keys.count - 1) * 8
    var x = point.x - total / 2
    for (index, key) in keys.enumerated() {
        let rect = CGRect(x: x, y: point.y, width: caps[index], height: capHeight)
        fill(rect, NSColor(white: 0.16, alpha: 0.96), radius: 9, in: ctx)
        stroke(rect, NSColor(white: 1, alpha: 0.16), radius: 9, in: ctx)
        text(key, at: CGPoint(x: rect.midX, y: rect.midY - 9), size: 22, color: Ink.text,
             weight: .semibold, align: .centre, in: ctx)
        x += caps[index] + 8
    }
    ctx.restoreGState()
}

/// The pointer, drawn rather than screenshotted so it renders at any size.
func drawCursor(at point: CGPoint, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    ctx.setShadow(offset: CGSize(width: 0, height: -2), blur: 6,
                  color: NSColor.black.withAlphaComponent(0.6).cgColor)
    let path = CGMutablePath()
    path.move(to: point)
    path.addLine(to: CGPoint(x: point.x, y: point.y - 26))
    path.addLine(to: CGPoint(x: point.x + 6.5, y: point.y - 19.5))
    path.addLine(to: CGPoint(x: point.x + 11, y: point.y - 28))
    path.addLine(to: CGPoint(x: point.x + 16, y: point.y - 25.5))
    path.addLine(to: CGPoint(x: point.x + 11.5, y: point.y - 17))
    path.addLine(to: CGPoint(x: point.x + 20, y: point.y - 16))
    path.closeSubpath()
    ctx.addPath(path)
    ctx.setFillColor(NSColor.white.cgColor)
    ctx.fillPath()
    ctx.restoreGState()
}

/// The agent's line, typed out a character at a time.
func drawPrompt(_ line: String, progress: Double, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    let shown = String(line.prefix(Int(Double(line.count) * min(max(progress, 0), 1))))
    let box = CGRect(x: size.width / 2 - 350, y: 42, width: 700, height: 60)
    fill(box, NSColor(white: 0.13, alpha: 0.97), radius: 14, in: ctx)
    stroke(box, Ink.accent.withAlphaComponent(0.5), radius: 14, width: 1.5, in: ctx)
    fill(CGRect(x: box.minX + 20, y: box.midY - 4, width: 8, height: 8), Ink.accent, radius: 4, in: ctx)
    text(shown, at: CGPoint(x: box.minX + 42, y: box.midY - 7), size: 18, color: Ink.text,
         mono: true, in: ctx)
    ctx.restoreGState()
}

func drawCaption(_ line: String, _ sub: String, alpha: CGFloat, in ctx: CGContext) {
    guard alpha > 0.01 else { return }
    ctx.saveGState()
    ctx.setAlpha(alpha)
    text(line, at: CGPoint(x: size.width / 2, y: 92), size: 34, color: Ink.text,
         weight: .semibold, align: .centre, in: ctx)
    text(sub, at: CGPoint(x: size.width / 2, y: 56), size: 17, color: Ink.dim,
         align: .centre, in: ctx)
    ctx.restoreGState()
}

// MARK: - The scene

let margin: CGFloat = 22
let deskTop = size.height - 34 - margin
let deskBottom: CGFloat = 128
let gap: CGFloat = 12

// Eight zones, in three columns of different widths and rows of different
// heights — a layout you draw once in the zone editor. Halves and quarters are
// what the Mac already does on its own; this is the reason to want Plonk, so
// the demo shows a desk full of windows landing in one, not three windows
// landing in thirds.
let deskLeft = margin
let deskWidth = size.width - margin * 2
let deskHeight = deskTop - deskBottom
let columns = (deskWidth - gap * 2)
let colOne = round(columns * 0.26)
let colTwo = round(columns * 0.44)
let colThree = columns - colOne - colTwo
let xTwo = deskLeft + colOne + gap
let xThree = xTwo + colTwo + gap

// Left column: a tall browser over a short finder.
let leftTopHeight = round((deskHeight - gap) * 0.56)
let zoneBrowser = CGRect(x: deskLeft, y: deskTop - leftTopHeight, width: colOne, height: leftTopHeight)
let zoneFiles = CGRect(x: deskLeft, y: deskBottom, width: colOne,
                       height: deskHeight - leftTopHeight - gap)
// Middle column: the editor, with two half-width panes beneath it.
let editorHeight = round((deskHeight - gap) * 0.68)
let zoneEditor = CGRect(x: xTwo, y: deskTop - editorHeight, width: colTwo, height: editorHeight)
let underHeight = deskHeight - editorHeight - gap
let underWidth = (colTwo - gap) / 2
let zoneTerminal = CGRect(x: xTwo, y: deskBottom, width: underWidth, height: underHeight)
let zoneTests = CGRect(x: xTwo + underWidth + gap, y: deskBottom, width: underWidth, height: underHeight)
// Right column: three equal rows.
let rightHeight = (deskHeight - gap * 2) / 3
let zoneLogs = CGRect(x: xThree, y: deskTop - rightHeight, width: colThree, height: rightHeight)
let zoneChat = CGRect(x: xThree, y: deskBottom + rightHeight + gap, width: colThree, height: rightHeight)
let zoneMail = CGRect(x: xThree, y: deskBottom, width: colThree, height: rightHeight)

let zones = [zoneBrowser, zoneFiles, zoneEditor, zoneTerminal, zoneTests, zoneLogs, zoneChat, zoneMail]

/// One window: where it starts on the pile, where it belongs, and when it goes.
struct Window {
    var title: String
    var hue: NSColor
    var messy: CGRect
    var home: CGRect
    var from: Double
    var to: Double
}

let green = NSColor(srgbRed: 0.36, green: 0.85, blue: 0.55, alpha: 1)
let violet = NSColor(srgbRed: 0.68, green: 0.55, blue: 1.0, alpha: 1)
let pink = NSColor(srgbRed: 1.0, green: 0.45, blue: 0.62, alpha: 1)
let teal = NSColor(srgbRed: 0.30, green: 0.80, blue: 0.82, alpha: 1)

// The pile: eight windows, cascaded and overlapping, a few running off the
// edges. It is the state the app exists to end, so it is worth drawing badly
// on purpose.
let windows = [
    // Dragged by hand, first beat.
    Window(title: "Browser", hue: Ink.accent,
           messy: CGRect(x: 96, y: 286, width: 560, height: 360), home: zoneBrowser,
           from: 0.7, to: 2.0),
    // Sent with a shortcut, second beat.
    Window(title: "Editor", hue: violet,
           messy: CGRect(x: 372, y: 214, width: 620, height: 400), home: zoneEditor,
           from: 2.8, to: 3.5),
    // The remaining six, all at once, when the sentence lands.
    Window(title: "Files", hue: teal,
           messy: CGRect(x: 58, y: 168, width: 430, height: 270), home: zoneFiles,
           from: 6.0, to: 6.9),
    Window(title: "Terminal", hue: green,
           messy: CGRect(x: 610, y: 150, width: 500, height: 300), home: zoneTerminal,
           from: 6.1, to: 7.0),
    Window(title: "Tests", hue: Ink.amber,
           messy: CGRect(x: 264, y: 132, width: 470, height: 290), home: zoneTests,
           from: 6.2, to: 7.1),
    Window(title: "Logs", hue: pink,
           messy: CGRect(x: 786, y: 330, width: 460, height: 300), home: zoneLogs,
           from: 6.3, to: 7.2),
    Window(title: "Chat", hue: Ink.accent,
           messy: CGRect(x: 148, y: 384, width: 400, height: 300), home: zoneChat,
           from: 6.4, to: 7.3),
    Window(title: "Mail", hue: green,
           messy: CGRect(x: 500, y: 400, width: 520, height: 290), home: zoneMail,
           from: 6.5, to: 7.4),
]

/// Which zone each window belongs to, so the overlay can light the right one.
let zoneOf: [String: Int] = ["Browser": 0, "Files": 1, "Editor": 2, "Terminal": 3,
                             "Tests": 4, "Logs": 5, "Chat": 6, "Mail": 7]

func frame(at t: Double) -> CGImage {
    let scale: CGFloat = 1
    let ctx = CGContext(data: nil, width: Int(size.width * scale), height: Int(size.height * scale),
                        bitsPerComponent: 8, bytesPerRow: 0,
                        space: CGColorSpaceCreateDeviceRGB(),
                        bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)!
    ctx.scaleBy(x: scale, y: scale)
    ctx.setAllowsAntialiasing(true)

    drawDesk(in: ctx)

    // Beat 1 (0.6-2.3s): one window dragged into its zone, by hand.
    // Beat 2 (2.6-3.7s): the next one sent there with a shortcut.
    // Beat 3 (4.0-7.5s): a sentence, and the other six go at once — the part
    // no amount of dragging and no built-in tiling gets you.
    let promptIn = phase(t, from: 4.0, to: 4.3)
    let typing = phase(t, from: 4.4, to: 6.0)

    // The overlay is drawn only while a window is being placed by hand or by
    // key, which is when the app actually draws it.
    let zonesShown = max(phase(t, from: 0.55, to: 0.85) - phase(t, from: 2.0, to: 2.35),
                         phase(t, from: 2.6, to: 2.8) - phase(t, from: 3.5, to: 3.8))
    var lit: Set<Int> = []
    if t >= 0.55 && t < 2.35 { lit = [zoneOf["Browser"]!] }
    if t >= 2.6 && t < 3.8 { lit = [zoneOf["Editor"]!] }

    // Each window sits on the pile until its moment, then eases home.
    let placed = windows.map { phase(t, from: $0.from, to: $0.to) }
    let panes = windows.enumerated().map { index, window in
        Pane(title: window.title, rect: lerp(window.messy, window.home, placed[index]),
             hue: window.hue)
    }
    // Back to front: the untouched pile, then what has landed, then whatever is
    // in flight — a moving window is the one you are meant to be watching.
    let order = panes.indices.sorted { a, b in
        func layer(_ index: Int) -> Int {
            if placed[index] <= 0 { return 0 }
            return placed[index] >= 1 ? 1 : 2
        }
        return layer(a) == layer(b) ? a > b : layer(a) < layer(b)
    }
    for index in order { draw(panes[index], in: ctx) }
    // Above the windows, exactly where the real overlay sits.
    drawZones(zones, highlighted: lit, alpha: CGFloat(zonesShown), in: ctx)

    // The pointer rides the first window in, then leaves.
    let cursorAlpha = phase(t, from: 0.3, to: 0.6) - phase(t, from: 2.1, to: 2.4)
    let grip = panes[0].rect
    drawCursor(at: CGPoint(x: grip.midX, y: grip.midY), alpha: CGFloat(cursorAlpha), in: ctx)

    // The shortcut that placed the second one: zone 3 is the editor's tile.
    drawKeys(["⌃", "⌥", "3"], centeredAt: CGPoint(x: size.width / 2, y: 44),
             alpha: CGFloat(phase(t, from: 2.6, to: 2.8) - phase(t, from: 3.5, to: 3.8)), in: ctx)

    drawPrompt("and the rest into the grid — logs and chat on the right",
               progress: typing,
               alpha: CGFloat(promptIn - phase(t, from: 7.6, to: 7.9)), in: ctx)

    drawCaption("Eight windows. One sentence.",
                "Plonk — draw any grid, then drag, press or say what goes where.",
                alpha: CGFloat(phase(t, from: 8.0, to: 8.4) - phase(t, from: 10.35, to: 10.5)),
                in: ctx)

    return ctx.makeImage()!
}

// MARK: - Output

let output = CommandLine.arguments.count > 1 ? CommandLine.arguments[1] : "/tmp/plonk-demo"
try? FileManager.default.createDirectory(atPath: output, withIntermediateDirectories: true)

let total = Int(duration * fps)
for index in 0..<total {
    let image = frame(at: Double(index) / fps)
    let rep = NSBitmapImageRep(cgImage: image)
    guard let data = rep.representation(using: .png, properties: [:]) else { continue }
    let name = String(format: "%s/frame-%04d.png", (output as NSString).utf8String!, index)
    try? data.write(to: URL(fileURLWithPath: name))
}
print("wrote \(total) frames to \(output)")
